//! MCP server implementation exposing Pix payment tools.
//!
//! Uses the `rmcp` crate to implement the Model Context Protocol server
//! with stdio transport, allowing AI agents to discover and invoke Pix tools.

use std::future::Future;
use std::pin::Pin;
use std::sync::Arc;

use chrono::{Duration, Utc};
use rmcp::{
    handler::server::{tool::ToolRouter, wrapper::Parameters},
    model::*,
    tool, tool_handler, tool_router, ServerHandler,
};

use pix_brcode::{encode_brcode, BrCode};
use pix_provider::{
    Balance, ChargeRequest, ChargeResponse, PixCharge, PixTransaction, PixTransfer, ProviderError,
    TransactionFilter,
};

use crate::tools::{
    CreateChargeParams, GenerateQrParams, GetChargeParams, ListTransactionsParams,
    SendPaymentParams,
};

/// Safety threshold for payments (in BRL).
/// Amounts above this trigger a warning in the response.
const PAYMENT_WARNING_THRESHOLD: f64 = 1000.0;

/// Object-safe version of `PixProvider` using boxed futures.
///
/// This trait enables dynamic dispatch for the MCP server, allowing
/// it to work with any provider implementation without generics.
pub trait DynPixProvider: Send + Sync {
    /// Creates a new immediate charge.
    fn create_charge(
        &self,
        request: ChargeRequest,
    ) -> Pin<Box<dyn Future<Output = Result<ChargeResponse, ProviderError>> + Send + '_>>;

    /// Retrieves a charge by txid.
    fn get_charge(
        &self,
        txid: String,
    ) -> Pin<Box<dyn Future<Output = Result<PixCharge, ProviderError>> + Send + '_>>;

    /// Gets the account balance.
    fn get_balance(
        &self,
    ) -> Pin<Box<dyn Future<Output = Result<Balance, ProviderError>> + Send + '_>>;

    /// Lists received Pix transactions.
    fn list_received_pix(
        &self,
        filter: TransactionFilter,
    ) -> Pin<Box<dyn Future<Output = Result<Vec<PixTransaction>, ProviderError>> + Send + '_>>;

    /// Sends a Pix payment.
    fn send_pix(
        &self,
        key: String,
        amount: String,
        description: Option<String>,
    ) -> Pin<Box<dyn Future<Output = Result<PixTransfer, ProviderError>> + Send + '_>>;
}

/// Blanket implementation: any `PixProvider` can be used as a `DynPixProvider`.
impl<T: pix_provider::PixProvider + Send + Sync> DynPixProvider for T {
    fn create_charge(
        &self,
        request: ChargeRequest,
    ) -> Pin<Box<dyn Future<Output = Result<ChargeResponse, ProviderError>> + Send + '_>> {
        Box::pin(pix_provider::PixProvider::create_charge(self, request))
    }

    fn get_charge(
        &self,
        txid: String,
    ) -> Pin<Box<dyn Future<Output = Result<PixCharge, ProviderError>> + Send + '_>> {
        Box::pin(async move { pix_provider::PixProvider::get_charge(self, &txid).await })
    }

    fn get_balance(
        &self,
    ) -> Pin<Box<dyn Future<Output = Result<Balance, ProviderError>> + Send + '_>> {
        Box::pin(pix_provider::PixProvider::get_balance(self))
    }

    fn list_received_pix(
        &self,
        filter: TransactionFilter,
    ) -> Pin<Box<dyn Future<Output = Result<Vec<PixTransaction>, ProviderError>> + Send + '_>> {
        Box::pin(pix_provider::PixProvider::list_received_pix(self, filter))
    }

    fn send_pix(
        &self,
        key: String,
        amount: String,
        description: Option<String>,
    ) -> Pin<Box<dyn Future<Output = Result<PixTransfer, ProviderError>> + Send + '_>> {
        Box::pin(async move {
            pix_provider::PixProvider::send_pix(self, &key, &amount, description.as_deref()).await
        })
    }
}

/// MCP server that exposes Pix payment operations as tools.
///
/// Wraps a `DynPixProvider` and exposes its operations as MCP tools
/// that AI agents can discover and invoke via the MCP protocol.
#[derive(Clone)]
pub struct PixMcpServer {
    /// The Pix provider used to execute API calls.
    provider: Arc<dyn DynPixProvider>,
    /// Default Pix key for the account.
    default_pix_key: Option<String>,
    /// Tool router generated by the `#[tool_router]` macro.
    tool_router: ToolRouter<Self>,
}

impl PixMcpServer {
    /// Creates a new MCP server with the given provider.
    ///
    /// # Arguments
    ///
    /// * `provider` - A Pix provider implementation (e.g., `EfiClient`).
    /// * `default_pix_key` - Optional default Pix key for charge creation.
    pub fn new(
        provider: impl pix_provider::PixProvider + 'static,
        default_pix_key: Option<String>,
    ) -> Self {
        Self {
            provider: Arc::new(provider),
            default_pix_key,
            tool_router: Self::tool_router(),
        }
    }

    /// Creates a new MCP server from a dynamic provider (primarily for testing).
    #[cfg(test)]
    pub fn from_dyn(provider: Arc<dyn DynPixProvider>, default_pix_key: Option<String>) -> Self {
        Self {
            provider,
            default_pix_key,
            tool_router: Self::tool_router(),
        }
    }
}

/// Helper to format a successful JSON result.
fn json_result<T: serde::Serialize>(value: &T) -> Result<CallToolResult, rmcp::ErrorData> {
    let json = serde_json::to_string_pretty(value)
        .map_err(|e| rmcp::ErrorData::internal_error(format!("serialization error: {e}"), None))?;
    Ok(CallToolResult::success(vec![Content::text(json)]))
}

/// Helper to format an error result (returns it as tool content, not MCP error).
fn error_result(msg: &str) -> Result<CallToolResult, rmcp::ErrorData> {
    Ok(CallToolResult::error(vec![Content::text(msg)]))
}

#[tool_router]
impl PixMcpServer {
    /// Create a Pix charge (cobrança) and return QR code / payment link.
    #[tool(description = "Create a Pix charge (cobrança) and return QR code / payment link")]
    async fn pix_create_charge(
        &self,
        Parameters(params): Parameters<CreateChargeParams>,
    ) -> Result<CallToolResult, rmcp::ErrorData> {
        if params.amount <= 0.0 {
            return error_result("Amount must be positive");
        }

        let key = params
            .pix_key
            .or_else(|| self.default_pix_key.clone())
            .ok_or_else(|| {
                rmcp::ErrorData::invalid_params("pix_key is required (no default configured)", None)
            })?;

        let request = ChargeRequest {
            pix_key: key,
            description: params.description,
            amount: format!("{:.2}", params.amount),
            expiration_secs: params.expiry_seconds.unwrap_or(3600),
            debtor: None,
            txid: None,
        };

        match self.provider.create_charge(request).await {
            Ok(response) => json_result(&response),
            Err(e) => error_result(&format!("Failed to create charge: {e}")),
        }
    }

    /// Check the status of a Pix charge by transaction ID.
    #[tool(description = "Check the status of a Pix charge by transaction ID")]
    async fn pix_get_charge(
        &self,
        Parameters(params): Parameters<GetChargeParams>,
    ) -> Result<CallToolResult, rmcp::ErrorData> {
        if params.txid.is_empty() {
            return error_result("txid cannot be empty");
        }

        match self.provider.get_charge(params.txid).await {
            Ok(charge) => json_result(&charge),
            Err(e) => error_result(&format!("Failed to get charge: {e}")),
        }
    }

    /// Get the current account balance.
    #[tool(description = "Get the current account balance")]
    async fn pix_check_balance(&self) -> Result<CallToolResult, rmcp::ErrorData> {
        match self.provider.get_balance().await {
            Ok(balance) => json_result(&balance),
            Err(e) => error_result(&format!("Failed to get balance: {e}")),
        }
    }

    /// List recent received Pix transactions.
    #[tool(description = "List recent received Pix transactions")]
    async fn pix_list_transactions(
        &self,
        Parameters(params): Parameters<ListTransactionsParams>,
    ) -> Result<CallToolResult, rmcp::ErrorData> {
        let days = params.days.unwrap_or(7);
        let now = Utc::now();
        let start = now - Duration::days(i64::from(days));

        let filter = TransactionFilter {
            start: Some(start),
            end: Some(now),
            page: None,
            per_page: Some(100),
        };

        match self.provider.list_received_pix(filter).await {
            Ok(transactions) => {
                let result = serde_json::json!({
                    "count": transactions.len(),
                    "period_days": days,
                    "transactions": transactions,
                });
                json_result(&result)
            }
            Err(e) => error_result(&format!("Failed to list transactions: {e}")),
        }
    }

    /// Send a Pix payment to a recipient.
    #[tool(description = "Send a Pix payment to a recipient")]
    async fn pix_send_payment(
        &self,
        Parameters(params): Parameters<SendPaymentParams>,
    ) -> Result<CallToolResult, rmcp::ErrorData> {
        if params.key.is_empty() {
            return error_result("Recipient key cannot be empty");
        }
        if params.amount <= 0.0 {
            return error_result("Amount must be positive");
        }

        let amount_str = format!("{:.2}", params.amount);

        let mut warning = String::new();
        if params.amount > PAYMENT_WARNING_THRESHOLD {
            warning = format!(
                "⚠️ WARNING: High-value payment of R$ {:.2}. Proceed with caution.\n",
                params.amount
            );
        }

        match self
            .provider
            .send_pix(params.key, amount_str, params.description)
            .await
        {
            Ok(transfer) => {
                let json = serde_json::to_string_pretty(&transfer).map_err(|e| {
                    rmcp::ErrorData::internal_error(format!("serialization error: {e}"), None)
                })?;
                let text = if warning.is_empty() {
                    json
                } else {
                    format!("{warning}{json}")
                };
                Ok(CallToolResult::success(vec![Content::text(text)]))
            }
            Err(e) => error_result(&format!("Failed to send payment: {e}")),
        }
    }

    /// Generate a static Pix QR code payload (offline, no API call).
    #[tool(description = "Generate a static Pix QR code payload (offline, no API call)")]
    async fn pix_generate_qr(
        &self,
        Parameters(params): Parameters<GenerateQrParams>,
    ) -> Result<CallToolResult, rmcp::ErrorData> {
        if params.key.is_empty() {
            return error_result("Pix key cannot be empty");
        }

        let name = params
            .merchant_name
            .unwrap_or_else(|| "PAGAMENTO PIX".to_string());
        let city_str = params.city.unwrap_or_else(|| "SAO PAULO".to_string());

        let mut builder = BrCode::builder(&params.key, &name, &city_str).point_of_initiation("11");

        if let Some(amt) = params.amount {
            if amt <= 0.0 {
                return error_result("Amount must be positive");
            }
            builder = builder.transaction_amount(&format!("{:.2}", amt));
        }

        let brcode = builder.build().map_err(|e| {
            rmcp::ErrorData::invalid_params(format!("Invalid QR code parameters: {e}"), None)
        })?;

        let payload = encode_brcode(&brcode);

        let result = serde_json::json!({
            "payload": payload,
            "pix_key": params.key,
            "amount": params.amount,
            "merchant_name": name,
            "city": city_str,
            "instructions": "Copy-paste this payload into any Pix-compatible banking app to pay."
        });

        json_result(&result)
    }
}

#[tool_handler]
impl ServerHandler for PixMcpServer {
    fn get_info(&self) -> ServerInfo {
        ServerInfo::new(ServerCapabilities::builder().enable_tools().build())
            .with_server_info(Implementation::new("pix-mcp", env!("CARGO_PKG_VERSION")))
            .with_instructions(
                "Pix CLI MCP Server — Make Pix payments, create charges, check balances, \
                 and generate QR codes from AI agents. Configure credentials via ~/.pixcli/config.toml"
                    .to_string(),
            )
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use chrono::Utc;
    use pix_provider::ProviderError;
    use std::sync::atomic::{AtomicU32, Ordering};

    /// A mock provider for testing MCP tools without real API calls.
    #[derive(Clone)]
    struct MockProvider {
        should_fail: bool,
        call_count: Arc<AtomicU32>,
    }

    impl MockProvider {
        fn new() -> Self {
            Self {
                should_fail: false,
                call_count: Arc::new(AtomicU32::new(0)),
            }
        }

        fn failing() -> Self {
            Self {
                should_fail: true,
                call_count: Arc::new(AtomicU32::new(0)),
            }
        }
    }

    impl DynPixProvider for MockProvider {
        fn create_charge(
            &self,
            request: ChargeRequest,
        ) -> Pin<Box<dyn Future<Output = Result<ChargeResponse, ProviderError>> + Send + '_>>
        {
            self.call_count.fetch_add(1, Ordering::SeqCst);
            let should_fail = self.should_fail;
            Box::pin(async move {
                if should_fail {
                    return Err(ProviderError::Http {
                        status: 500,
                        message: "mock error".to_string(),
                    });
                }
                Ok(ChargeResponse {
                    txid: "mock_txid_001".to_string(),
                    brcode: "00020126...mock".to_string(),
                    status: pix_provider::ChargeStatus::Active,
                    created_at: Utc::now(),
                    expires_at: Utc::now() + Duration::seconds(i64::from(request.expiration_secs)),
                })
            })
        }

        fn get_charge(
            &self,
            txid: String,
        ) -> Pin<Box<dyn Future<Output = Result<PixCharge, ProviderError>> + Send + '_>> {
            self.call_count.fetch_add(1, Ordering::SeqCst);
            let should_fail = self.should_fail;
            Box::pin(async move {
                if should_fail {
                    return Err(ProviderError::Http {
                        status: 404,
                        message: "charge not found".to_string(),
                    });
                }
                Ok(PixCharge {
                    txid,
                    status: pix_provider::ChargeStatus::Active,
                    amount: "10.00".to_string(),
                    pix_key: "test@example.com".to_string(),
                    description: Some("Test charge".to_string()),
                    brcode: Some("00020126...".to_string()),
                    debtor: None,
                    created_at: Utc::now(),
                    expires_at: Utc::now() + Duration::hours(1),
                    e2eids: vec![],
                })
            })
        }

        fn get_balance(
            &self,
        ) -> Pin<Box<dyn Future<Output = Result<Balance, ProviderError>> + Send + '_>> {
            self.call_count.fetch_add(1, Ordering::SeqCst);
            let should_fail = self.should_fail;
            Box::pin(async move {
                if should_fail {
                    return Err(ProviderError::Http {
                        status: 500,
                        message: "balance unavailable".to_string(),
                    });
                }
                Ok(Balance {
                    available: "1234.56".to_string(),
                })
            })
        }

        fn list_received_pix(
            &self,
            _filter: TransactionFilter,
        ) -> Pin<Box<dyn Future<Output = Result<Vec<PixTransaction>, ProviderError>> + Send + '_>>
        {
            self.call_count.fetch_add(1, Ordering::SeqCst);
            let should_fail = self.should_fail;
            Box::pin(async move {
                if should_fail {
                    return Err(ProviderError::Http {
                        status: 500,
                        message: "list failed".to_string(),
                    });
                }
                Ok(vec![
                    PixTransaction {
                        e2eid: "E001".to_string(),
                        txid: Some("tx001".to_string()),
                        amount: "50.00".to_string(),
                        payer_name: Some("João Silva".to_string()),
                        payer_document: None,
                        description: Some("Payment".to_string()),
                        timestamp: Utc::now(),
                    },
                    PixTransaction {
                        e2eid: "E002".to_string(),
                        txid: None,
                        amount: "25.00".to_string(),
                        payer_name: None,
                        payer_document: None,
                        description: None,
                        timestamp: Utc::now(),
                    },
                ])
            })
        }

        fn send_pix(
            &self,
            _key: String,
            amount: String,
            _description: Option<String>,
        ) -> Pin<Box<dyn Future<Output = Result<PixTransfer, ProviderError>> + Send + '_>> {
            self.call_count.fetch_add(1, Ordering::SeqCst);
            let should_fail = self.should_fail;
            Box::pin(async move {
                if should_fail {
                    return Err(ProviderError::Http {
                        status: 500,
                        message: "transfer failed".to_string(),
                    });
                }
                Ok(PixTransfer {
                    e2eid: "E12345678901234567890123456789012".to_string(),
                    id_envio: "mock_envio_001".to_string(),
                    amount,
                    status: "REALIZADO".to_string(),
                    timestamp: Utc::now(),
                })
            })
        }
    }

    fn make_server() -> PixMcpServer {
        PixMcpServer::from_dyn(
            Arc::new(MockProvider::new()),
            Some("test@example.com".to_string()),
        )
    }

    fn make_failing_server() -> PixMcpServer {
        PixMcpServer::from_dyn(
            Arc::new(MockProvider::failing()),
            Some("test@example.com".to_string()),
        )
    }

    fn make_server_no_key() -> PixMcpServer {
        PixMcpServer::from_dyn(Arc::new(MockProvider::new()), None)
    }

    fn extract_text(result: &CallToolResult) -> String {
        result
            .content
            .iter()
            .filter_map(|c| match &c.raw {
                RawContent::Text(t) => Some(t.text.clone()),
                _ => None,
            })
            .collect::<Vec<_>>()
            .join("\n")
    }

    // ─── Tool Discovery ────────────────────────────────────────

    #[test]
    fn test_tool_discovery_has_six_tools() {
        let server = make_server();
        let tools = server.tool_router.list_all();
        assert_eq!(
            tools.len(),
            6,
            "Expected 6 tools, got {}: {:?}",
            tools.len(),
            tools.iter().map(|t| &t.name).collect::<Vec<_>>()
        );
    }

    #[test]
    fn test_tool_names() {
        let server = make_server();
        let tools = server.tool_router.list_all();
        let names: Vec<String> = tools.iter().map(|t| t.name.to_string()).collect();
        assert!(names.iter().any(|n| n == "pix_create_charge"));
        assert!(names.iter().any(|n| n == "pix_get_charge"));
        assert!(names.iter().any(|n| n == "pix_check_balance"));
        assert!(names.iter().any(|n| n == "pix_list_transactions"));
        assert!(names.iter().any(|n| n == "pix_send_payment"));
        assert!(names.iter().any(|n| n == "pix_generate_qr"));
    }

    #[test]
    fn test_tools_have_descriptions() {
        let server = make_server();
        let tools = server.tool_router.list_all();
        for tool in &tools {
            assert!(
                tool.description.is_some(),
                "Tool {} has no description",
                tool.name
            );
        }
    }

    #[test]
    fn test_tools_have_input_schemas() {
        let server = make_server();
        let tools = server.tool_router.list_all();
        for tool in &tools {
            // input_schema is an Arc<Map<String, Value>> — non-empty means it exists
            let _schema = &tool.input_schema;
            // Just assert it doesn't panic when accessed
        }
    }

    #[test]
    fn test_server_info() {
        let server = make_server();
        let info = server.get_info();
        assert!(info.capabilities.tools.is_some());
        assert!(info.instructions.is_some());
    }

    #[test]
    fn test_server_info_name_and_version() {
        let server = make_server();
        let info = server.get_info();
        assert_eq!(info.server_info.name, "pix-mcp");
    }

    // ─── pix_check_balance ─────────────────────────────────────

    #[tokio::test]
    async fn test_check_balance_success() {
        let server = make_server();
        let result = server.pix_check_balance().await.unwrap();
        assert!(!result.is_error.unwrap_or(false));
        let text = extract_text(&result);
        assert!(text.contains("1234.56"));
    }

    #[tokio::test]
    async fn test_check_balance_failure() {
        let server = make_failing_server();
        let result = server.pix_check_balance().await.unwrap();
        let text = extract_text(&result);
        assert!(text.contains("Failed to get balance"));
    }

    // ─── pix_create_charge ─────────────────────────────────────

    #[tokio::test]
    async fn test_create_charge_success() {
        let server = make_server();
        let params = CreateChargeParams {
            amount: 10.50,
            pix_key: None,
            description: Some("Test".to_string()),
            expiry_seconds: None,
        };
        let result = server.pix_create_charge(Parameters(params)).await.unwrap();
        assert!(!result.is_error.unwrap_or(false));
        let text = extract_text(&result);
        assert!(text.contains("mock_txid_001"));
    }

    #[tokio::test]
    async fn test_create_charge_with_explicit_key() {
        let server = make_server();
        let params = CreateChargeParams {
            amount: 25.00,
            pix_key: Some("other@key.com".to_string()),
            description: None,
            expiry_seconds: Some(1800),
        };
        let result = server.pix_create_charge(Parameters(params)).await.unwrap();
        assert!(!result.is_error.unwrap_or(false));
    }

    #[tokio::test]
    async fn test_create_charge_zero_amount() {
        let server = make_server();
        let params = CreateChargeParams {
            amount: 0.0,
            pix_key: None,
            description: None,
            expiry_seconds: None,
        };
        let result = server.pix_create_charge(Parameters(params)).await.unwrap();
        let text = extract_text(&result);
        assert!(text.contains("Amount must be positive"));
    }

    #[tokio::test]
    async fn test_create_charge_negative_amount() {
        let server = make_server();
        let params = CreateChargeParams {
            amount: -5.0,
            pix_key: None,
            description: None,
            expiry_seconds: None,
        };
        let result = server.pix_create_charge(Parameters(params)).await.unwrap();
        let text = extract_text(&result);
        assert!(text.contains("Amount must be positive"));
    }

    #[tokio::test]
    async fn test_create_charge_no_key() {
        let server = make_server_no_key();
        let params = CreateChargeParams {
            amount: 10.0,
            pix_key: None,
            description: None,
            expiry_seconds: None,
        };
        let result = server.pix_create_charge(Parameters(params)).await;
        assert!(result.is_err(), "Should fail without pix_key");
    }

    #[tokio::test]
    async fn test_create_charge_api_error() {
        let server = make_failing_server();
        let params = CreateChargeParams {
            amount: 10.0,
            pix_key: None,
            description: None,
            expiry_seconds: None,
        };
        let result = server.pix_create_charge(Parameters(params)).await.unwrap();
        let text = extract_text(&result);
        assert!(text.contains("Failed to create charge"));
    }

    // ─── pix_get_charge ────────────────────────────────────────

    #[tokio::test]
    async fn test_get_charge_success() {
        let server = make_server();
        let params = GetChargeParams {
            txid: "tx001".to_string(),
        };
        let result = server.pix_get_charge(Parameters(params)).await.unwrap();
        assert!(!result.is_error.unwrap_or(false));
        let text = extract_text(&result);
        assert!(text.contains("tx001"));
    }

    #[tokio::test]
    async fn test_get_charge_empty_txid() {
        let server = make_server();
        let params = GetChargeParams {
            txid: String::new(),
        };
        let result = server.pix_get_charge(Parameters(params)).await.unwrap();
        let text = extract_text(&result);
        assert!(text.contains("txid cannot be empty"));
    }

    #[tokio::test]
    async fn test_get_charge_not_found() {
        let server = make_failing_server();
        let params = GetChargeParams {
            txid: "nonexistent".to_string(),
        };
        let result = server.pix_get_charge(Parameters(params)).await.unwrap();
        let text = extract_text(&result);
        assert!(text.contains("Failed to get charge"));
    }

    // ─── pix_list_transactions ─────────────────────────────────

    #[tokio::test]
    async fn test_list_transactions_default_days() {
        let server = make_server();
        let params = ListTransactionsParams { days: None };
        let result = server
            .pix_list_transactions(Parameters(params))
            .await
            .unwrap();
        assert!(!result.is_error.unwrap_or(false));
        let text = extract_text(&result);
        assert!(text.contains("\"count\": 2"));
        assert!(text.contains("\"period_days\": 7"));
    }

    #[tokio::test]
    async fn test_list_transactions_custom_days() {
        let server = make_server();
        let params = ListTransactionsParams { days: Some(30) };
        let result = server
            .pix_list_transactions(Parameters(params))
            .await
            .unwrap();
        let text = extract_text(&result);
        assert!(text.contains("\"period_days\": 30"));
    }

    #[tokio::test]
    async fn test_list_transactions_failure() {
        let server = make_failing_server();
        let params = ListTransactionsParams { days: None };
        let result = server
            .pix_list_transactions(Parameters(params))
            .await
            .unwrap();
        let text = extract_text(&result);
        assert!(text.contains("Failed to list transactions"));
    }

    // ─── pix_send_payment ──────────────────────────────────────

    #[tokio::test]
    async fn test_send_payment_success() {
        let server = make_server();
        let params = SendPaymentParams {
            key: "recipient@email.com".to_string(),
            amount: 100.00,
            description: Some("Payment".to_string()),
        };
        let result = server.pix_send_payment(Parameters(params)).await.unwrap();
        assert!(!result.is_error.unwrap_or(false));
        let text = extract_text(&result);
        assert!(text.contains("REALIZADO"));
    }

    #[tokio::test]
    async fn test_send_payment_high_value_warning() {
        let server = make_server();
        let params = SendPaymentParams {
            key: "key@test.com".to_string(),
            amount: 5000.00,
            description: None,
        };
        let result = server.pix_send_payment(Parameters(params)).await.unwrap();
        let text = extract_text(&result);
        assert!(text.contains("WARNING"));
        assert!(text.contains("5000.00"));
    }

    #[tokio::test]
    async fn test_send_payment_empty_key() {
        let server = make_server();
        let params = SendPaymentParams {
            key: String::new(),
            amount: 10.0,
            description: None,
        };
        let result = server.pix_send_payment(Parameters(params)).await.unwrap();
        let text = extract_text(&result);
        assert!(text.contains("Recipient key cannot be empty"));
    }

    #[tokio::test]
    async fn test_send_payment_zero_amount() {
        let server = make_server();
        let params = SendPaymentParams {
            key: "key@test.com".to_string(),
            amount: 0.0,
            description: None,
        };
        let result = server.pix_send_payment(Parameters(params)).await.unwrap();
        let text = extract_text(&result);
        assert!(text.contains("Amount must be positive"));
    }

    #[tokio::test]
    async fn test_send_payment_negative_amount() {
        let server = make_server();
        let params = SendPaymentParams {
            key: "key@test.com".to_string(),
            amount: -10.0,
            description: None,
        };
        let result = server.pix_send_payment(Parameters(params)).await.unwrap();
        let text = extract_text(&result);
        assert!(text.contains("Amount must be positive"));
    }

    #[tokio::test]
    async fn test_send_payment_failure() {
        let server = make_failing_server();
        let params = SendPaymentParams {
            key: "key@test.com".to_string(),
            amount: 10.0,
            description: None,
        };
        let result = server.pix_send_payment(Parameters(params)).await.unwrap();
        let text = extract_text(&result);
        assert!(text.contains("Failed to send payment"));
    }

    // ─── pix_generate_qr ──────────────────────────────────────

    #[tokio::test]
    async fn test_generate_qr_basic() {
        let server = make_server();
        let params = GenerateQrParams {
            key: "test@email.com".to_string(),
            amount: None,
            merchant_name: None,
            city: None,
        };
        let result = server.pix_generate_qr(Parameters(params)).await.unwrap();
        assert!(!result.is_error.unwrap_or(false));
        let text = extract_text(&result);
        assert!(text.contains("payload"));
        assert!(text.contains("test@email.com"));
    }

    #[tokio::test]
    async fn test_generate_qr_with_amount() {
        let server = make_server();
        let params = GenerateQrParams {
            key: "test@email.com".to_string(),
            amount: Some(99.99),
            merchant_name: Some("LOJA TESTE".to_string()),
            city: Some("BRASILIA".to_string()),
        };
        let result = server.pix_generate_qr(Parameters(params)).await.unwrap();
        let text = extract_text(&result);
        assert!(text.contains("payload"));
        assert!(text.contains("99.99"));
        assert!(text.contains("LOJA TESTE"));
        assert!(text.contains("BRASILIA"));
    }

    #[tokio::test]
    async fn test_generate_qr_empty_key() {
        let server = make_server();
        let params = GenerateQrParams {
            key: String::new(),
            amount: None,
            merchant_name: None,
            city: None,
        };
        let result = server.pix_generate_qr(Parameters(params)).await.unwrap();
        let text = extract_text(&result);
        assert!(text.contains("Pix key cannot be empty"));
    }

    #[tokio::test]
    async fn test_generate_qr_negative_amount() {
        let server = make_server();
        let params = GenerateQrParams {
            key: "key@test.com".to_string(),
            amount: Some(-10.0),
            merchant_name: None,
            city: None,
        };
        let result = server.pix_generate_qr(Parameters(params)).await.unwrap();
        let text = extract_text(&result);
        assert!(text.contains("Amount must be positive"));
    }

    #[tokio::test]
    async fn test_generate_qr_long_merchant_name() {
        let server = make_server();
        let params = GenerateQrParams {
            key: "key@test.com".to_string(),
            amount: None,
            merchant_name: Some("A".repeat(30)),
            city: None,
        };
        let result = server.pix_generate_qr(Parameters(params)).await;
        // Should return an MCP error from BrCode validation
        assert!(result.is_err());
    }

    #[tokio::test]
    async fn test_generate_qr_payload_is_valid_emv() {
        let server = make_server();
        let params = GenerateQrParams {
            key: "test@email.com".to_string(),
            amount: Some(10.00),
            merchant_name: Some("LOJA".to_string()),
            city: Some("CITY".to_string()),
        };
        let result = server.pix_generate_qr(Parameters(params)).await.unwrap();
        let text = extract_text(&result);
        let json: serde_json::Value = serde_json::from_str(&text).unwrap();
        let payload = json["payload"].as_str().unwrap();
        // EMV payloads start with "0002" (payload format indicator tag)
        assert!(
            payload.starts_with("0002"),
            "EMV payload should start with '0002': {}",
            payload
        );
        assert!(payload.len() > 8);
    }

    // ─── Provider call counting ────────────────────────────────

    #[tokio::test]
    async fn test_provider_called_once_per_tool() {
        let provider = Arc::new(MockProvider::new());
        let server = PixMcpServer::from_dyn(provider.clone(), Some("key@test.com".to_string()));

        assert_eq!(provider.call_count.load(Ordering::SeqCst), 0);

        let _ = server.pix_check_balance().await;
        assert_eq!(provider.call_count.load(Ordering::SeqCst), 1);

        let params = GetChargeParams {
            txid: "tx1".to_string(),
        };
        let _ = server.pix_get_charge(Parameters(params)).await;
        assert_eq!(provider.call_count.load(Ordering::SeqCst), 2);
    }
}
